# Generated by Django 5.2.8 on 2025-11-15 11:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Medico",
            fields=[
                ("id_medico", models.AutoField(primary_key=True, serialize=False)),
                ("nombre", models.CharField(max_length=100)),
                ("apellido", models.CharField(max_length=100)),
                ("especialidad", models.CharField(max_length=100)),
                ("telefono", models.CharField(max_length=20)),
                ("email", models.EmailField(max_length=100)),
                ("licencia_medica", models.CharField(max_length=50)),
                ("salario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("fecha_contratacion", models.DateField()),
            ],
        ),
    ]
