# Generated by Django 5.2.8 on 2025-11-15 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Habitacion",
            fields=[
                ("id_habitacion", models.AutoField(primary_key=True, serialize=False)),
                ("numero_habitacion", models.CharField(max_length=10, unique=True)),
                (
                    "tipo_habitacion",
                    models.CharField(
                        choices=[
                            ("individual", "Individual"),
                            ("doble", "Doble"),
                            ("suite", "Suite"),
                            ("uci", "UCI"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "estado_habitacion",
                    models.CharField(
                        choices=[
                            ("disponible", "Disponible"),
                            ("ocupada", "Ocupada"),
                            ("mantenimiento", "En Mantenimiento"),
                            ("limpieza", "En Limpieza"),
                        ],
                        max_length=50,
                    ),
                ),
                ("costo_diario", models.DecimalField(decimal_places=2, max_digits=10)),
                ("capacidad", models.IntegerField()),
                ("descripcion", models.TextField(blank=True, null=True)),
            ],
        ),
    ]
